import re
from xml.etree import ElementTree as ET

NS = 'urn:oasis:names:tc:xliff:document:1.2'
ET.register_namespace('', NS)

OLD_FILE = 'src/locale/messages.en.xlf'
NEW_FILE = 'src/locale/messages.xlf'
OUT_FILE = 'src/locale/messages.en.xlf'

def parse_units(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        text = f.read()
    units = []
    pattern = re.compile(r'<trans-unit[^>]*id="([^"]*)"[^>]*>(.*?)</trans-unit>', re.DOTALL)
    for m in pattern.finditer(text):
        uid = m.group(1)
        inner = m.group(2)
        sm = re.search(r'(<source>.*?</source>)', inner, re.DOTALL)
        source_xml = sm.group(1) if sm else ''
        units.append((uid, source_xml, m.group(0)))
    return units

def source_to_target_map(units):
    mapping = {}
    for uid, sxml, full in units:
        tm = re.search(r'(<target>.*?</target>)', full, re.DOTALL)
        if tm:
            mapping[sxml] = tm.group(1)
    return mapping

KNOWN = {
    ' Procesando pago... ': ' Processing payment... ',
    ' Confirmar Reserva ': ' Confirm Reservation ',
    ' Ocultar ': ' Hide ',
    ' Agregar descuento ': ' Add discount ',
    'Año': 'Year', 'Mes': 'Month',
    'Enero': 'January', 'Febrero': 'February', 'Marzo': 'March',
    'Abril': 'April', 'Mayo': 'May', 'Junio': 'June',
    'Julio': 'July', 'Agosto': 'August', 'Septiembre': 'September',
    'Octubre': 'October', 'Noviembre': 'November', 'Diciembre': 'December',
    'Total generado por reservas confirmadas': 'Total generated by confirmed reservations',
    'Facturación diaria por reservas': 'Daily billing from reservations',
    'Sesión cerrada correctamente.': 'Session closed successfully.',
    'Éxito': 'Success',
    'Metodos de pago': 'Payment methods',
    'Detalle de tarifa': 'Rate detail',
    'Resumen de la reserva': 'Reservation summary',
    'Seleccion de tipo de cuenta': 'Account type selection',
    'Cargando hotel...': 'Loading hotel...',
    'Hotel no disponible': 'Hotel not available',
    'Cargando dirección...': 'Loading address...',
    'Dirección no disponible': 'Address not available',
    'Cargando país...': 'Loading country...',
    'País no disponible': 'Country not available',
    'Cargando Usuario...': 'Loading user...',
    'Cargando Hotel...': 'Loading hotel...',
    'Activo': 'Active',
    'Inactivo': 'Inactive',
    'Error cargando países': 'Error loading countries',
    'Check-In Confirmado!': 'Check-In Confirmed!',
    'Código de la reserva': 'Reservation code',
    'Detalles de la reserva': 'Reservation details',
    'Hotel:': 'Hotel:',
    'Habitación:': 'Room:',
    'Check-In:': 'Check-In:',
    'Check-Out:': 'Check-Out:',
    'Error en el Check-In': 'Check-In Error',
}

PH_MAP = {
    'Metodo de pago': 'Payment method',
    'Imagen de': 'Image of',
    'Mapa de': 'Map of',
}

old_units = parse_units(OLD_FILE)
old_map = source_to_target_map(old_units)
print(f"Old: {len(old_units)} units, {len(old_map)} with targets")

new_units = parse_units(NEW_FILE)
print(f"New: {len(new_units)} units")

with open(NEW_FILE, 'r', encoding='utf-8') as f:
    new_text = f.read()

def inner_text(sxml):
    m = re.match(r'<source>(.*)</source>', sxml, re.DOTALL)
    return m.group(1) if m else ''

unmatched = []
for uid, sxml, full in new_units:
    if sxml in old_map:
        old_target = old_map[sxml]
        new_entry = sxml + old_target
        if sxml in new_text:
            new_text = new_text.replace(sxml, new_entry, 1)
        else:
            unmatched.append((uid, sxml[:60]))
    else:
        inner = inner_text(sxml)
        stripped = inner.strip()
        # Match by stripped text in KNOWN
        if stripped in KNOWN:
            txml = f'<target>{KNOWN[stripped]}</target>'
            new_entry = sxml + txml
            if sxml in new_text:
                new_text = new_text.replace(sxml, new_entry, 1)
            else:
                unmatched.append((uid, f"known not found: {stripped[:40]}"))
        # Match placeholder sources: text <x id="PH" equiv-text="..."/>
        elif '<x ' in inner:
            m = re.match(r'^([^<]+)\s*<x[^>]*/>$', inner.strip())
            if m:
                prefix = m.group(1).strip()
                if prefix in PH_MAP:
                    txml = f'<target>{PH_MAP[prefix]} <x id="PH" equiv-text=""/></target>'
                    new_entry = sxml + txml
                    if sxml in new_text:
                        new_text = new_text.replace(sxml, new_entry, 1)
                    else:
                        unmatched.append((uid, f"ph not found: {prefix}"))
                else:
                    unmatched.append((uid, f"PH prefix unknown: {prefix}"))
            else:
                unmatched.append((uid, f"PH unparseable: {inner[:60]}"))
        elif 'Ingreso total - ' in inner:
            full_inner = inner[len('Ingreso total - '):]
            txml = f'<target>Total Income - {full_inner}</target>'
            new_entry = sxml + txml
            if sxml in new_text:
                new_text = new_text.replace(sxml, new_entry, 1)
            else:
                unmatched.append((uid, "income title failed"))
        else:
            unmatched.append((uid, f"NO MATCH: {stripped[:60]}"))

new_text = new_text.replace(
    '<file source-language="es" datatype="plaintext" original="ng2.template">',
    '<file source-language="es" target-language="en" datatype="plaintext" original="ng2.template">'
)

with open(OUT_FILE, 'w', encoding='utf-8') as f:
    f.write(new_text)

print(f"\nOutput: {len(re.findall(r'<target>', new_text))} targets")
if unmatched:
    print(f"\nWARNING: {len(unmatched)} unmatched:")
    for uid, reason in unmatched[:30]:
        print(f"  {uid}: {reason}")
else:
    print("ALL UNITS MATCHED!")
